# Numpy

Biblioteca para operações numéricas do Python.

- [Array](#array)
    - [Gerando arrays](#gerando)
    - [Indexando](#indexando)
        - [Array 1-D](#1d)
        - [Array N-D](#nd)
    - [Operações](#operacoes)
        - [Com um escalar](#operacoes-escalar)
        - [Com um outro array](#operacoes-array)
    - [Funções Importantes](#funcoes)
        - [Sum](#sum)
        - [Reshape](#reshape)
        - [Argmax](#argmax)
        - [Arange](#arange)
- [Teste de velocidade](#velocidade)
    - [Multiplicação por constante](#mult)
    - [Soma por linha](#sumlines)
    - [Argmax](#vargmax)

In [2]:
# Importando a biblioteca
import numpy as np


## <span id='array'>Array</span>
Generalização de vetor com qualquer número de dimenções. É um dos conceitos centrais do NumPy

![Array](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png "array")

In [3]:
l = np.array([1, 2, 3, 4, 5])

print(l)
print(l.shape) # Shape é o tamanho da array em cada dimensão
l[0] = 23 # Podemos alterar o valor de uma entrada da array
print(l)

[1 2 3 4 5]
(5,)
[23  2  3  4  5]


In [4]:
l = np.array([[1, 2, 3], [4, 5, 6]]) # Pode ter duas dimensões

print(l)
print(l.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# Podemos acessar cada elemento do shape
l.shape[0]

2

**PERGUNTA:** Qual o shape de uma imagem RGB com dimensões 1280x720? E de uma base de dados com 5000 destas imagens?

### <span id="gerando">Gerando arrays</span>
Além de arrays com valores específicos temos outras formas de criar esses objetos

In [5]:
a = np.zeros((2,2)) #Cria um array só com zeros com shape (2,2)
a

array([[0., 0.],
       [0., 0.]])

In [8]:
a = np.ones((2,2)) #Cria um array só com uns com shape (2,2)
a

array([[1., 1.],
       [1., 1.]])

In [6]:
a = np.random.random((3,2)) #Cria um array de shape (3,2) com valores aleatórios
a

array([[0.15699201, 0.64219653],
       [0.55383287, 0.00718484],
       [0.70564534, 0.3051629 ]])

In [7]:
a = np.random.randint(20, size=(3,2)) # Cria um array com valores aleatorios inteiros (20 é o valor maxímo)
a

array([[12, 10],
       [ 1, 18],
       [14, 14]])

In [11]:
np.arange(5) # Cria um vetor de 0 a 4

array([0, 1, 2, 3, 4])

### <span id="indexando">Indexando arrays</span>

#### <span id="1d">Array 1D</span>

In [8]:
a = np.random.randint(50, size=(10,))
a

array([47, 22, 24, 46, 48,  3, 27, 32, 33,  0])

In [9]:
print(a[2]) # Igual ao python puro
print(a[:4]) # Igual ao python puro
print(a[3:6]) # Igual ao python puro

24
[47 22 24 46]
[46 48  3]


In [14]:
idx = np.array([0,2,3]) # Podemos usar outra array para indexar só algumas posições
a[idx]

array([44, 29, 12])

In [15]:
maior10 = a > 10 # Array de booleanos indicando se é maior que 10
maior10

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
print(a[maior10]) # Printa só os valores True do outro array
print(a[a > 10]) # Não precisa da variável intermediaria

[39 35 17 35 23 19 40]
[39 35 17 35 23 19 40]


#### <span id="nd">Array N-D</span>

In [10]:
a = np.random.randint(50, size=(4,6))
print(a)

[[10 34 22 28  6  8]
 [16 44 14 28 49 31]
 [13  3 19  4 40  4]
 [27 38 31 30  6  1]]


In [11]:
print(a[1][4]) # [Linha][Coluna] - Igual ao python puro
print(a[1,4]) # [Linha, Coluna] - Separando por virgula

49
49


In [14]:
print(a[1:3,2:5]) # Slicing normal

[[14 28 49]
 [19  4 40]]


In [15]:
print(a[:,5]) # ':' significa deixar a dimesão inteira (toda o coluna, nesse caso)

[ 8 31  4  1]


In [16]:
print(a[2,:]) # ':' significa deixar a dimesão inteira (toda a linha, nesse caso)

[13  3 19  4 40  4]


### <span id="operacoes">Operações</span>

In [16]:
a = np.random.randint(10, size=(5,))
b = np.random.randint(10, size=(5,))

print(a)
print(b)

[1 9 0 2 7]
[1 9 5 5 0]


In [17]:
# Soma
print(a + b)
print(np.add(a, b))

[ 2 18  5  7  7]
[ 2 18  5  7  7]


In [18]:
a + 10 # Soma 10 em cada elemento

array([11, 19, 10, 12, 17])

In [19]:
a ** 2

array([ 1, 81,  0,  4, 49])

In [20]:
# Multiplicação element-wise
print(a * b)
print(np.multiply(a, b))

[ 1 81  0 10  0]
[ 1 81  0 10  0]


In [21]:
a = np.random.randint(10, size=(5,2))
b = np.random.randint(10, size=(2,4))

print(a)
print(b)

[[1 9]
 [1 5]
 [7 9]
 [0 6]
 [6 1]]
[[8 0 6 5]
 [3 8 1 8]]


In [22]:
# Soma
print(a + b)
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (5,2) (2,4) 

![No](https://media.giphy.com/media/ly8G39g1ujpNm/giphy.gif "no")

In [23]:
a = np.random.randint(10, size=(10,4))
b = np.random.randint(10, size=(4))

print(a)
print(b)

[[4 3 9 0]
 [3 1 4 0]
 [1 1 3 3]
 [0 5 3 6]
 [9 0 7 9]
 [3 9 5 8]
 [2 9 0 4]
 [4 5 8 2]
 [6 7 0 9]
 [3 3 4 1]]
[3 3 6 2]


In [24]:
a + b

array([[ 7,  6, 15,  2],
       [ 6,  4, 10,  2],
       [ 4,  4,  9,  5],
       [ 3,  8,  9,  8],
       [12,  3, 13, 11],
       [ 6, 12, 11, 10],
       [ 5, 12,  6,  6],
       [ 7,  8, 14,  4],
       [ 9, 10,  6, 11],
       [ 6,  6, 10,  3]])

### <span id="matematica">Funções matemática</span>

In [25]:
print(a)
print(a.T) # Faz a transposta da matrix

[[4 3 9 0]
 [3 1 4 0]
 [1 1 3 3]
 [0 5 3 6]
 [9 0 7 9]
 [3 9 5 8]
 [2 9 0 4]
 [4 5 8 2]
 [6 7 0 9]
 [3 3 4 1]]
[[4 3 1 0 9 3 2 4 6 3]
 [3 1 1 5 0 9 9 5 7 3]
 [9 4 3 3 7 5 0 8 0 4]
 [0 0 3 6 9 8 4 2 9 1]]


In [26]:
# Multiplicação de matrizes (Ou produto escalar, se fossem dois vetores)
print(np.dot(a, b))

[75 36 30 45 87 82 41 79 57 44]


In [27]:
# Multiplicação de matrizes (com outra notação)
print(a @ b)

[75 36 30 45 87 82 41 79 57 44]


In [28]:
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

print(a)
print(b)

[8 9 2 1 1]
[2 1 5 9 7]


In [29]:
np.dot(a, b) # produto escalar

51

In [33]:
# Sistema linear 
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
print(a)
print(b)
np.linalg.solve(a, b)

[[3 1]
 [1 2]]
[9 8]


array([2., 3.])

### <span id="funcoes">Funções importantes</span>

In [34]:
a = np.random.randint(10, size=(8,4))
print(a)

[[8 0 7 3]
 [9 1 5 5]
 [1 8 5 6]
 [0 1 9 4]
 [0 5 8 0]
 [0 7 3 5]
 [3 6 4 3]
 [2 2 8 3]]


#### <span id="sum"> Sum <span>

In [35]:
# Soma todos os valores de a
np.sum(a)

131

In [36]:
# Soma todos os valores de a em cada um dos eixos
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[23 30 49 29]
[18 20 20 14 13 15 16 15]


Essas operações sobre eixos são **muito importantes** (Por causa da representação matricial dos dados)

#### <span id="reshape"> Reshape </span>

In [39]:
print(a.shape)
b = a.reshape(16,2) # Importante: Isso retorna o objeto com o novo formato, não é inplace
print(b.shape)

print(a)
print(b)

(8, 4)
(16, 2)
[[8 0 7 3]
 [9 1 5 5]
 [1 8 5 6]
 [0 1 9 4]
 [0 5 8 0]
 [0 7 3 5]
 [3 6 4 3]
 [2 2 8 3]]
[[8 0]
 [7 3]
 [9 1]
 [5 5]
 [1 8]
 [5 6]
 [0 1]
 [9 4]
 [0 5]
 [8 0]
 [0 7]
 [3 5]
 [3 6]
 [4 3]
 [2 2]
 [8 3]]


In [38]:
print(a)
b = a.reshape(-1,16) # Colacando -1 ele deixa do tamanho necessário para fazer sentido
print(b)

[[8 0 7 3]
 [9 1 5 5]
 [1 8 5 6]
 [0 1 9 4]
 [0 5 8 0]
 [0 7 3 5]
 [3 6 4 3]
 [2 2 8 3]]
[[8 0 7 3 9 1 5 5 1 8 5 6 0 1 9 4]
 [0 5 8 0 0 7 3 5 3 6 4 3 2 2 8 3]]


**EXERCÍCIO:** Como criar essa matriz em uma linha no numpy, sem for, usando só as funções passadas até então?

In [40]:
# Output desejado
print(np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]]))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
# Código aqui
np.arange(1,10).reshape(3,3).T 

# np.arange(1,10) => [1 2 3 4 5 6 7 8 9]

# np.arange(1,10).reshape(3,3) =>
    # [[1 2 3]
    # [4 5 6]
    # [7 8 9]]

#np.arange(1,10).reshape(3,3) =>
       #[[1, 4, 7],
       #[2, 5, 8],
       #[3, 6, 9]]

    

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**EXERCÍCIO:** Supondo a base de dados com 5000 imagens RGB de 1280x720, como eu transformo essa base para que cada imagem seja só um vetor de uma dimensão?

In [52]:
SIZE = (5000,1280,720,3) # Coloque aqui a tupla com as dimençoes iniciais da base
imagens = np.random.randint(10, size=SIZE)
#imagens.shape[0]
#imagens.reshape(imagens.shape[0],1280,720,-1)
# ...

MemoryError: 

#### <span id="argmax"> Argmax </span>

In [51]:
a = np.random.randint(50, size=(12,))
print(a)

[ 1 19 10 34 11 37 19 46 39 15 46 12]


In [52]:
print(np.argmax(a)) # Retorna o indice do maior elemento
print(a[np.argmax(a)]) # Para pegar o valor do maior elemento

7
46


#### <span id="arange"> Arange </span>

In [53]:
exemplo = np.arange(0, 1500, 150) # Gera números entre dois valores com um passo determinado
print(exemplo)

[   0  150  300  450  600  750  900 1050 1200 1350]


**EXERCÍCIO:** Crie uma matriz aleatória e pegue o indice do maior elemento para cada linha e depois para cada coluna

In [65]:
m = np.random.randint(50,size=(3,3))



[[18 28 16]
 [46 18 32]
 [18 45 12]]
Maior de cada Linha 
[46 18 32]


## <span id="velocidade"> Teste de velocidade </span>

![Speed](https://media1.tenor.com/images/cea1d72266eec94333e2897f8ee86bf1/tenor.gif?itemid=5593970 "speed")

### <span id="mult"> Multiplicação por constante </span>

In [67]:
a = [[j for j in range(10000)] for _ in range(1000)]
b = np.array(a)


array([[   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       ...,
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999],
       [   0,    1,    2, ..., 9997, 9998, 9999]])

In [68]:
%%time
for i in range(len(a)):
    for j in range(len(a[0])):
        a[i][j] *= 10

CPU times: user 1.78 s, sys: 19.5 ms, total: 1.8 s
Wall time: 1.8 s


In [69]:
%%time
b *= 10

CPU times: user 12.5 ms, sys: 52 µs, total: 12.6 ms
Wall time: 13 ms


### <span id="sumlines"> Soma por linha</span>

In [73]:
%%time
sums = []
for i in range(len(a)):
    part_sum = 0
    for j in range(len(a[0])):
        part_sum += a[i][j]
    sums.append(part_sum)

CPU times: user 1.66 s, sys: 0 ns, total: 1.66 s
Wall time: 1.66 s


In [72]:
%%time
b.sum(axis=1).shape

CPU times: user 23.8 ms, sys: 3.65 ms, total: 27.4 ms
Wall time: 28.1 ms


(1000,)

### <span id="vargmax"> Argmax </span>

In [61]:
a = [i for i in range(10000000)]
b = np.array(a)

In [62]:
%%time
idx = 0
for i in range(len(a)):
    if a[i] > a[idx]:
        idx = i

CPU times: user 1.64 s, sys: 0 ns, total: 1.64 s
Wall time: 1.64 s


In [63]:
%%time
np.argmax(b);

CPU times: user 19.2 ms, sys: 0 ns, total: 19.2 ms
Wall time: 18.9 ms


9999999