# Numpy

Biblioteca para operações numéricas do Python.

- [Array](#array)
    - [Gerando arrays](#gerando)
    - [Indexando](#indexando)
        - [Array 1-D](#1d)
        - [Array N-D](#nd)
    - [Operações](#operacoes)
        - [Com um escalar](#operacoes-escalar)
        - [Com um outro array](#operacoes-array)
    - [Funções Importantes](#funcoes)
        - [Sum](#sum)
        - [Reshape](#reshape)
        - [Argmax](#argmax)
        - [Arange](#arange)
- [Teste de velocidade](#velocidade)
    - [Multiplicação por constante](#mult)
    - [Soma por linha](#sumlines)
    - [Argmax](#vargmax)

In [4]:
# Importando a biblioteca
import numpy as np


## <span id='array'>Array</span>
Generalização de vetor com qualquer número de dimenções. É um dos conceitos centrais do NumPy

![Array](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png "array")

In [5]:
l = np.array([1, 2, 3, 4, 5])

print(l)
print(l.shape) # Shape é o tamanho da array em cada dimensão
l[0] = 23 # Podemos alterar o valor de uma entrada da array
print(l)

[1 2 3 4 5]
(5,)
[23  2  3  4  5]


In [6]:
l = np.array([[1, 2, 3], [4, 5, 6]]) # Pode ter duas dimensões

print(l)
print(l.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
# Podemos acessar cada elemento do shape
l.shape[0]

2

**PERGUNTA:** Qual o shape de uma imagem RGB com dimensões 1280x720? E de uma base de dados com 5000 destas imagens?

### <span id="gerando">Gerando arrays</span>
Além de arrays com valores específicos temos outras formas de criar esses objetos

In [8]:
a = np.zeros((2,2)) #Cria um array só com zeros com shape (2,2)
a

array([[0., 0.],
       [0., 0.]])

In [9]:
a = np.ones((2,2)) #Cria um array só com uns com shape (2,2)
a

array([[1., 1.],
       [1., 1.]])

In [10]:
a = np.random.random((3,2)) #Cria um array de shape (3,2) com valores aleatórios
a

array([[0.17982711, 0.27166405],
       [0.57580363, 0.70458652],
       [0.52587569, 0.58502345]])

In [11]:
a = np.random.randint(20, size=(3,2)) # Cria um array com valores aleatorios inteiros (20 é o valor maxímo)
a

array([[ 7, 16],
       [ 3, 13],
       [19, 12]])

In [12]:
np.arange(5) # Cria um vetor de 0 a 4

array([0, 1, 2, 3, 4])

### <span id="indexando">Indexando arrays</span>

#### <span id="1d">Array 1D</span>

In [13]:
a = np.random.randint(50, size=(10,))
a

array([ 8,  0, 39, 35, 17,  2, 35, 23, 19, 40])

In [14]:
print(a[2]) # Igual ao python puro
print(a[:4]) # Igual ao python puro
print(a[3:6]) # Igual ao python puro

39
[ 8  0 39 35]
[35 17  2]


In [15]:
idx = np.array([0,2,3]) # Podemos usar outra array para indexar só algumas posições
a[idx]

array([ 8, 39, 35])

In [16]:
maior10 = a > 10 # Array de booleanos indicando se é maior que 10
maior10

array([False, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [17]:
print(a[maior10]) # Printa só os valores True do outro array
print(a[a > 10]) # Não precisa da variável intermediaria

[39 35 17 35 23 19 40]
[39 35 17 35 23 19 40]


#### <span id="nd">Array N-D</span>

In [18]:
a = np.random.randint(50, size=(4,6))
print(a)

[[25 38 24 47  3 40]
 [33 16  7 38 32 13]
 [24 33 22 38 13  1]
 [34 40  1 46 15 18]]


In [19]:
print(a[1][4]) # [Linha][Coluna] - Igual ao python puro
print(a[1,4]) # [Linha, Coluna] - Separando por virgula

32
32


In [20]:
print(a[1:3,2:5]) # Slicing normal

[[ 7 38 32]
 [22 38 13]]


In [24]:
print(a[:,5]) # ':' significa deixar a dimesão inteira (toda o coluna, nesse caso)

[40 13  1 18]


In [25]:
print(a[2,:]) # ':' significa deixar a dimesão inteira (toda a linha, nesse caso)

[24 33 22 38 13  1]


### <span id="operacoes">Operações</span>

In [26]:
a = np.random.randint(10, size=(5,))
b = np.random.randint(10, size=(5,))

print(a)
print(b)

[3 9 3 6 2]
[4 3 7 4 2]


In [27]:
# Soma
print(a + b)
print(np.add(a, b))

[ 7 12 10 10  4]
[ 7 12 10 10  4]


In [28]:
a + 10 # Soma 10 em cada elemento

array([13, 19, 13, 16, 12])

In [29]:
a ** 2

array([ 9, 81,  9, 36,  4])

In [30]:
# Multiplicação element-wise
print(a * b)
print(np.multiply(a, b))

[12 27 21 24  4]
[12 27 21 24  4]


In [31]:
a = np.random.randint(10, size=(5,2))
b = np.random.randint(10, size=(2,4))

print(a)
print(b)

[[2 1]
 [0 4]
 [1 5]
 [6 3]
 [8 5]]
[[5 9 5 1]
 [7 9 9 0]]


In [32]:
# Soma
print(a + b)
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (5,2) (2,4) 

![No](https://media.giphy.com/media/ly8G39g1ujpNm/giphy.gif "no")

In [33]:
a = np.random.randint(10, size=(10,4))
b = np.random.randint(10, size=(4))

print(a)
print(b)

[[5 9 8 7]
 [4 6 5 0]
 [4 8 7 0]
 [5 2 5 4]
 [4 9 1 3]
 [7 6 5 7]
 [9 6 2 5]
 [7 3 2 2]
 [6 5 7 1]
 [5 0 0 4]]
[0 3 7 9]


In [34]:
a + b

array([[ 5, 12, 15, 16],
       [ 4,  9, 12,  9],
       [ 4, 11, 14,  9],
       [ 5,  5, 12, 13],
       [ 4, 12,  8, 12],
       [ 7,  9, 12, 16],
       [ 9,  9,  9, 14],
       [ 7,  6,  9, 11],
       [ 6,  8, 14, 10],
       [ 5,  3,  7, 13]])

### <span id="matematica">Funções matemática</span>

In [35]:
print(a)
print(a.T) # Faz a transposta da matrix

[[5 9 8 7]
 [4 6 5 0]
 [4 8 7 0]
 [5 2 5 4]
 [4 9 1 3]
 [7 6 5 7]
 [9 6 2 5]
 [7 3 2 2]
 [6 5 7 1]
 [5 0 0 4]]
[[5 4 4 5 4 7 9 7 6 5]
 [9 6 8 2 9 6 6 3 5 0]
 [8 5 7 5 1 5 2 2 7 0]
 [7 0 0 4 3 7 5 2 1 4]]


In [36]:
# Multiplicação de matrizes (Ou produto escalar, se fossem dois vetores)
print(np.dot(a, b))

[146  53  73  77  61 116  77  41  73  36]


In [37]:
# Multiplicação de matrizes (com outra notação)
print(a @ b)

[146  53  73  77  61 116  77  41  73  36]


In [38]:
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

print(a)
print(b)

[0 2 7 2 9]
[1 4 2 5 7]


In [39]:
np.dot(a, b) # produto escalar

95

In [40]:
# Sistema linear 
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
np.linalg.solve(a, b)

array([2., 3.])

### <span id="funcoes">Funções importantes</span>

In [41]:
a = np.random.randint(10, size=(8,4))
print(a)

[[2 1 9 8]
 [0 7 7 0]
 [0 2 0 7]
 [6 6 4 5]
 [0 6 6 6]
 [0 2 2 7]
 [4 3 8 4]
 [9 9 4 8]]


#### <span id="sum"> Sum <span>

In [42]:
# Soma todos os valores de a
np.sum(a)

142

In [43]:
# Soma todos os valores de a em cada um dos eixos
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[21 36 40 45]
[20 14  9 21 18 11 19 30]


Essas operações sobre eixos são **muito importantes** (Por causa da representação matricial dos dados)

#### <span id="reshape"> Reshape </span>

In [44]:
print(a.shape)
b = a.reshape(16,2) # Importante: Isso retorna o objeto com o novo formato, não é inplace
print(b.shape)

(8, 4)
(16, 2)


In [45]:
print(a)
b = a.reshape(-1,16) # Colacando -1 ele deixa do tamanho necessário para fazer sentido
print(b)

[[2 1 9 8]
 [0 7 7 0]
 [0 2 0 7]
 [6 6 4 5]
 [0 6 6 6]
 [0 2 2 7]
 [4 3 8 4]
 [9 9 4 8]]
[[2 1 9 8 0 7 7 0 0 2 0 7 6 6 4 5]
 [0 6 6 6 0 2 2 7 4 3 8 4 9 9 4 8]]


**EXERCÍCIO:** Como criar essa matriz em uma linha no numpy, sem for, usando só as funções passadas até então?

In [46]:
# Output desejado
print(np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]]))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [49]:
# Código aqui
np.arange(1,10).reshape(3,3).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**EXERCÍCIO:** Supondo a base de dados com 5000 imagens RGB de 1280x720, como eu transformo essa base para que cada imagem seja só um vetor de uma dimensão?

In [50]:
SIZE = (5000,1280,720,3) # Coloque aqui a tupla com as dimençoes iniciais da base
imagens = np.random.randint(255, size=SIZE)
imagens.reshape(imagens.shape[0],-1)
# ...

MemoryError: 

#### <span id="argmax"> Argmax </span>

In [51]:
a = np.random.randint(50, size=(12,))
print(a)

[ 1 19 10 34 11 37 19 46 39 15 46 12]


In [52]:
print(np.argmax(a)) # Retorna o indice do maior elemento
print(a[np.argmax(a)]) # Para pegar o valor do maior elemento

7
46


#### <span id="arange"> Arange </span>

In [53]:
exemplo = np.arange(0, 1500, 150) # Gera números entre dois valores com um passo determinado
print(exemplo)

[   0  150  300  450  600  750  900 1050 1200 1350]


**EXERCÍCIO:** Crie uma matriz aleatória e pegue o indice do maior elemento para cada linha e depois para cada coluna

## <span id="velocidade"> Teste de velocidade </span>

![Speed](https://media1.tenor.com/images/cea1d72266eec94333e2897f8ee86bf1/tenor.gif?itemid=5593970 "speed")

### <span id="mult"> Multiplicação por constante </span>

In [54]:
a = [[j for j in range(10000)] for _ in range(1000)]
b = np.array(a)

In [55]:
%%time
for i in range(len(a)):
    for j in range(len(a[0])):
        a[i][j] *= 10

CPU times: user 1.66 s, sys: 1.36 ms, total: 1.66 s
Wall time: 1.66 s


In [56]:
%%time
b *= 10

CPU times: user 10.4 ms, sys: 3.87 ms, total: 14.3 ms
Wall time: 14.6 ms


### <span id="sumlines"> Soma por linha</span>

In [59]:
%%time
sums = []
for i in range(len(a)):
    part_sum = 0
    for j in range(len(a[0])):
        part_sum += a[i][j]
    sums.append(part_sum)

CPU times: user 1.6 s, sys: 0 ns, total: 1.6 s
Wall time: 1.6 s


In [60]:
%%time
b.sum(axis=1).shape

CPU times: user 10.2 ms, sys: 706 µs, total: 10.9 ms
Wall time: 10.2 ms


(1000,)

### <span id="vargmax"> Argmax </span>

In [61]:
a = [i for i in range(10000000)]
b = np.array(a)

In [62]:
%%time
idx = 0
for i in range(len(a)):
    if a[i] > a[idx]:
        idx = i

CPU times: user 1.64 s, sys: 0 ns, total: 1.64 s
Wall time: 1.64 s


In [63]:
%%time
np.argmax(b);

CPU times: user 19.2 ms, sys: 0 ns, total: 19.2 ms
Wall time: 18.9 ms


9999999